### ISSUE TITLE
Namespaces.setPrefix() returns true when data is not set 

### ISSUE THREAD

**Issue by christopher-johnson** [trellis-ldp/trellis-rosid-common#3]
I notice that in the [JDK-9 Travis build](https://travis-ci.org/trellis-ldp/trellis-docker-karaf/jobs/281952090) the namespace test fails.  What is odd is that if you run the test again it works, so it could be compiler related.  

Not sure if this is the reason, but Curator `NodeCache` says "it's not possible to stay transactionally in sync.  Users of this class must  be prepared for false-positives and false-negatives".   

In the screenshot, you can see that `data` does not contain the jsonld namespace after it was supposed to have been set [here](https://github.com/trellis-ldp/trellis-rosid-common/blob/master/src/test/java/org/trellisldp/rosid/common/NamespacesTest.java#L107).

![screenshot at 2017-10-01 19 17 06](https://user-images.githubusercontent.com/5990301/31057147-f44182ac-a6dd-11e7-8be0-fba029c6bfcb.png)

**Comment by acoburn** [comment]
Which compiler are you using? I have been using the oracle JDKs.

**Comment by christopher-johnson** [comment]
You can see from the build log that this happened on travis that used the oracle JDK.  Using travis ensures that this was not something unique to my configuration, which can easily get screwy, primarily because of IntelliJ not being fully geared to work with the Gradle 1.9 VM.  

I am looking into how ZK connection state can be managed with Curator.  Do you think that connection state should have a handler?  The cache example has one.  Is it always assumed that the connection is there before a set, because when the test fails, I guess it is because there is no connection, but this state would not throw, so it seems that catch is unreachable.

**Comment by christopher-johnson** [comment]
I think that I have understood this problem.  It is not related at all to Curator or Zookeeper, but is the Jackson Object Mapper.  My theory (yet not totally proven) is that there are different symbols used for objects in Java 9 than what Jackson is expecting, perhaps because it was compiled with 1.8.  So, when the mapper returns a String, for example, and then you do a getBytes on the string, you see garbage at the front of the string like `�� t r` which was the symbol for the HashMap that Jackson left behind. It is not clear to me why it works on successive runs, but perhaps Jackson can reflect the runtime?

**Comment by christopher-johnson** [comment]
After more investigation, this first theory is not correct.  See attached test output with incremental logging.  

![screenshot at 2017-10-03 18 38 01](https://user-images.githubusercontent.com/5990301/31137154-a6f0be30-a86a-11e7-994d-f41af190663d.png)

getNamespaces() is actually called _again_ after the test assertion fails, and it will return the expected response.  I commented out all of the assertions after the [failing one](https://github.com/trellis-ldp/trellis-rosid-common/blob/master/src/test/java/org/trellisldp/rosid/common/NamespacesTest.java#L108), so the test should end. 
 
Perhaps, the problem is because getNamespaces() overrides a non-package (trellis-spi) method and there are two class loaders working asynchronously?  idk, this one is a real jigsaw puzzle.
  
Also, the test always fails for me when run with gradlew at the CLI.  
`$ ../gradlew clean test --tests "org.trellisldp.rosid.common.NamespacesTest.testWriteNamespaces"`

**Comment by christopher-johnson** [comment]
For reference, here is the output from same test run with 1.8...
![screenshot at 2017-10-03 19 27 16](https://user-images.githubusercontent.com/5990301/31139273-414051c0-a871-11e7-8cf3-1f98a09fbd9a.png)

**Comment by christopher-johnson** [comment]
finally I have made it work by removing `@Override` from `getNamespaces()`!

![screenshot at 2017-10-03 20 07 16](https://user-images.githubusercontent.com/5990301/31141022-7f10cd68-a876-11e7-8850-d190df669139.png)

I guess that this is not really a fix, but maybe there is another workaround.  At least the cause is known now.

**Comment by acoburn** [comment]
@christopher-johnson I changed the namespace cache implementation so that these async issues should be less of a problem. Feel free to re-open this issue if you find that this doesn't fix things.
